version: 2
orbs:
  node: circleci/node@12.16.1
jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
         steps:
           - run: npm install
      - run: npm run test
      
