version: 2.0
jobs:
  build:
    docker:
      - image: docker:18.06.0-ce-git
    steps:
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: echo build
          command: echo "build workflow"
  deploy:
    working_directory: /
    docker:
      - image: docker:18.06.0-ce-git
    steps:
      - run:
          name: echo something
          command: echo "deploy workflow"

workflows:
  version: 2
  build_step:
    jobs:
      - build:
          filters:
            branches:
              only: /^[0-9]+\.[0-9]+(\.[0-9]+)?|abc12-.*/
      - deploy:
          reqires:
            - build
          filters:
            branches:
              only: /^[0-9]+\.[0-9]+(\.[0-9]+)?|abc12-.*/