version: 2.0
jobs:
  build:
    docker:
    - image: docker:18.06.0-ce-git
    steps:
    - checkout
    - run: git version

workflows:
  version: 2
  build_step:
    jobs:
      - build:
          filters:
            branches:
              only: /^[0-9]+\.[0-9]+(\.[0-9]+)?|abc12-.*/